### PR TITLE
Scala3 support

### PR DESCRIPTION
**Pull request by petitviolet**
Updated repository to support Scala 3.0.0.
https://github.com/sangria-graphql/sangria/issues/653

### CODE REVIEW

**Comment by petitviolet** [comment]
Could anyone take a look at this PR? Let me know if anything I'm missing. Thank you!

**Comment by sh0hei** [comment]
Thanks for PR @petitviolet !
I'll review it in the next few days 🙏

**Review by sh0hei — APPROVED** [review]

**Comment by sh0hei** [comment]
Thanks, @petitviolet !

**Comment by petitviolet** [comment]
Thank you for the review and merge!

**Pull request merged**
